CREATE TABLE [dbo].[Medication]
(
	[Id] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [Din] BIGINT NOT NULL, 
	[PersonId] BIGINT NOT NULL, 
    [PrescriptionId] BIGINT NULL, 
    [Name] NVARCHAR(255) NOT NULL, 
	[Dosage] NVARCHAR(255) NOT NULL, 
    [Strength] FLOAT NOT NULL, 
	[Units] NVARCHAR(55) NOT NULL, 
	[Format] NVARCHAR(55) NOT NULL,
	[Instructions] NVARCHAR(255) NOT NULL, 
	[NumRefills] INT NOT NULL, 
    [RemainingPills] FLOAT NOT NULL, 
	[PharmacyObtained] NVARCHAR(255) NOT NULL, 
    [Image] VARBINARY(MAX) NULL, 
    [TakeAsNeeded] BIT NOT NULL, 
    [SideEffects] NVARCHAR(255) NOT NULL,
	[DateObtained] DATETIME NOT NULL, 
)